project_id = "fyssbzgmhnolazjfwafm"

[functions.send-completion-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.auto-release-documents]
verify_jwt = false

[functions.nowpayments]
verify_jwt = false

[functions.send-payment-verified-email]
verify_jwt = false

[functions.admin-send-email]
verify_jwt = false

[functions.viva-payments]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.notify-document-upload]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.ai-admin-helper]
verify_jwt = false

[functions.process-bulk-reports]
verify_jwt = false

[functions.send-customer-notification]
verify_jwt = false

[functions.handle-unsubscribe]
verify_jwt = false
