project_id = "fyssbzgmhnolazjfwafm"

[functions.send-completion-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.auto-release-documents]
verify_jwt = false

[functions.nowpayments]
verify_jwt = false

[functions.send-payment-verified-email]
verify_jwt = false

[functions.admin-send-email]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.notify-document-upload]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.ai-admin-helper]
verify_jwt = false

[functions.send-customer-notification]
verify_jwt = false

[functions.handle-unsubscribe]
verify_jwt = false

[functions.notify-pending-documents]
verify_jwt = false

[functions.expire-crypto-payments]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.verify-stripe-payment]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-receipt]
verify_jwt = false

[functions.generate-receipt-pdf]
verify_jwt = false

[functions.generate-bank-statement-pdf]
verify_jwt = false

[functions.create-dodo-checkout]
verify_jwt = false

[functions.dodo-webhook]
verify_jwt = false

[functions.expire-credits]
verify_jwt = false

[functions.similarity-auto-map]
verify_jwt = false
