project_id = "fyssbzgmhnolazjfwafm"

[functions.send-completion-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.auto-release-documents]
verify_jwt = false

[functions.nowpayments]
verify_jwt = false

[functions.send-payment-verified-email]
verify_jwt = false
